### ISSUE TITLE
`match` expression tracking issue

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/tasm-lang#60]
We're adding support match expressions that return values such that they can be used in bindings. This will allow us to write 

```rust
let a: u32 = match an_enum {
    Enum::A(x) => {
        let val: u32 = x * 2;
        val
    }
    Enum::B(x, y) => {
        ...
    }
};
```

- [x] Allow `panic` and `assert` to be the returned value from an arm-body
- [x] Allow wild-card arm-patterns -- match statements already support this
- [x] Add support match expressions on boxed enums
- [x] Test implementation through `ProofItem`
- [x] Do compile-time wildcard condition evaluation instead of runtime as we do now
- [x] Test that `panic!` actually crashes VM execution

This work currently takes place on the [`proof-item`](https://github.com/TritonVM/tasm-lang/tree/proof-item) branch.
